### PR TITLE
Added Public Modifiers

### PR DESCRIPTION
**Pull request by Alonski**
Adding Public, Pure etc modifiers as well as other tiny fixes.
Going a few files at a time as per @GriffGreen request :)

BTW what is VaultMock?

### CODE REVIEW

**Comment by GriffGreen** [comment]
Vault Mock is for testing

**Comment by Alonski** [comment]
Shouldn't VaultMock be named vaultMock? Or is it capitalized on purpose?

**Comment by jbaylina** [comment]
Cotract names are Capitalized (Like classes)

**Comment by perissology** [comment]
Thanks!

**Pull request merged**
