### PR TITLE
add owned from giveth-common

### LINKED ISSUE #28: Use the contracts in the common-contract-deps repo Specifically Owned.sol
https://github.com/Giveth/common-contract-deps/tree/master/contracts

### PR DESCRIPTION
**Pull request by Quazia**
Added the `Owened.sol` contract from the giveth-common-contracts repository.

resolves #28

### CODE REVIEW

**Comment by jbaylina** [comment]
Perfect!!, please fix conflicts

**Comment by Quazia** [comment]
Alright, I think I got them but I'm not sure since it's the auto-generated files so I have a feeling the checksums are going to be off... not sure what to do about that.

**Comment by jbaylina** [comment]
Check the conflicts, but probably this is added in another PR

**Comment by perissology** [comment]
closing this as we are making the vault `Escable` which inherits `Owned`. #55 

Thanks

**Pull request closed without merging**
