### PR TITLE
Adding Comments, Adding Public modifiers, Fixing Linting errors and warnings

### PR DESCRIPTION
**Pull request by Alonski**
This pull request is a work in progress
Want to get input if this looks to be a good idea.

Adding comments, fixing errors and adding modifiers where needed

### CODE REVIEW

**Comment by GriffGreen** [comment]
is there a stronger yes than FUCK YEAH?! If so, insert here ;-D 

But i must request that we change the structure a little bit. 

Please break this up into many smaller PRs. 

The comments can go into the Comment branch and there you can feel more free to make larger PRs, if thats easier, just make sure that you and Arthur aren't doing the same functions.

For code changes, you want to use smaller PRs and they will get a couple eyes on them... the first set of eye's are Travis's 

note that your build failed.... you can find where by clicking the details link next to `continuous-integration/travis-ci/pr — The Travis CI build failed`

@adriamb built an awesome system to confirm that PRs dont break our tests, so it is strongly recommended that you make smaller PRs and confirm they get a check mark before merging them.

That being said, I am loving the beatification!!! Thanx for adding all the public modifiers and all the comments. This is exactly what i had hoped to see :-D 

Thank you man!

**Comment by perissology** [comment]
fyi, I'm almost certain the failed build is not your fault. They are test timeouts due to travis-ci running tests slower then our local machines, and will be fixed in #34.

**Comment by Quazia** [comment]
Yeah doesn't look like there's _too_ much overlap, mostly just in the `ILiquidPledgingPlugin` file so that's lucky.

**Comment by Alonski** [comment]
@GriffGreen So do you want me to close this and start over with splitting the commits?

**Pull request closed without merging**
